controllers:
    resource: ../src/PL/Controller/
    type: attribute

app_logout:
    path: /logout
    methods: GET

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /tournaments
        permanent: false